name: Compile and Release Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [release, debug]

    steps:
      - uses: actions/checkout@v4

      - name: Clone current vcpkg version
        run: git clone https://github.com/microsoft/vcpkg "${{ github.workspace }}/vcpkg"

      - name: Setup MSVC on Windows
        uses: ilammy/msvc-dev-cmd@v1
        if: matrix.os == 'windows-latest'

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Create CMakeUserPresets.json
        run: |
          touch ${{ github.workspace }}/CMakeUserPresets.json
          echo '{
              "version": 2,
              "configurePresets": [
                {
                  "name": "release",
                  "inherits": "vcpkg-release",
                  "environment": {
                    "VCPKG_ROOT": "./vcpkg"
                  }
                },
                {
                  "name": "debug",
                  "inherits": "vcpkg-debug",
                  "environment": {
                    "VCPKG_ROOT": "./vcpkg"
                  }
                }
              ]
            }' > ${{ github.workspace }}/CMakeUserPresets.json
          cat ${{ github.workspace }}/CMakeUserPresets.json

      - name: Configure CMake
        run: cmake --preset=${{ matrix.build_type }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build

      - name: Rename
        run: mv ${{ github.workspace }}/build/immuno-endocrine-cpp${{ matrix.os == 'windows-latest' && '.exe' || '' }} ${{ github.workspace }}/build/immuno-endocrine-cpp-${{ matrix.os }}-${{ matrix.build_type }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}

      - uses: actions/upload-artifact@v4
        with:
          name: immuno-endocrine-cpp-${{ matrix.os }}-${{ matrix.build_type }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}
          path: ${{ github.workspace }}/build/immuno-endocrine-cpp-${{ matrix.os }}-${{ matrix.build_type }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}

  release:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Get current date
        run: echo "current_date=$(date +%Y-%m-%dT%H%M)" >> $GITHUB_ENV

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.current_date }}',
              sha: context.sha
            })

      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: ${{ github.workspace }}/artifacts

      - name: Display structure of downloaded files
        run: ls -R ${{ github.workspace }}/artifacts

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.current_date }}
          files: |
            ${{ github.workspace }}/artifacts/immuno-endocrine-cpp-macos-latest-debug
            ${{ github.workspace }}/artifacts/immuno-endocrine-cpp-macos-latest-release
            ${{ github.workspace }}/artifacts/immuno-endocrine-cpp-ubuntu-latest-debug
            ${{ github.workspace }}/artifacts/immuno-endocrine-cpp-ubuntu-latest-release
            ${{ github.workspace }}/artifacts/immuno-endocrine-cpp-windows-latest-debug.exe
            ${{ github.workspace }}/artifacts/immuno-endocrine-cpp-windows-latest-release.exe
