name: Populate dependencies

on:
  push:
    branches: [main]

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_FEATURE_FLAGS: dependencygraph

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clone current vcpkg version
        run: git clone https://github.com/microsoft/vcpkg "${{ github.workspace }}/vcpkg"

      - name: List vcpkg directory
        run: ls -R "${{ github.workspace }}/vcpkg"

      - name: Run vcpkg
        run: ${{ github.workspace }}/vcpkg/vcpkg install --dry-run
