name: Populate Dependencies

on:
  push:
    branches: [main]

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_FEATURE_FLAGS: dependencygraph

jobs:
  generate-graph:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run vcpkg
        run: vcpkg install --dry-run --debug
