name: Compile and Release Project

on:
  push:
    branches: [$default-branch, github-actions]
  pull_request:
    branches: [$default-branch]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ github.sha }}',
              sha: context.sha
            })
